# Generated by Django 2.1.1 on 2018-10-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181006_1515'),
        ('api', '0006_category_description'),
    ]

    operations = [
    ]
